server:
  port: 8080

spring:
  application:
    name: gateway-service
  autoconfigure:
    exclude:
      - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orgdirectory-service
          uri: lb://orgdirectory-service
          predicates:
            - Path=/orgdirectory/**
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations(?<segment>/?.*), /web-module/api/organizations${segment}
    loadbalancer:
      enabled: true

    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: false
        register-health-check: false
        service-name: organization-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.loadbalancer.core.RoundRobinLoadBalancer: DEBUG
    org.springframework.cloud.loadbalancer.cache: DEBUG
